stages:
- stage: MyBashStage
  jobs:
  - job: MyBashJob
    pool: Azure Pipelines
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'  # You can also use a script file
        script: 'echo "Hello from Bash on Azure Pipelines Agent!"'  # Your bash commands here